#!/usr/bin/env bash
# Regenerate .agent/NAVMAP.md — a symbol index for targeted reads of large files.
# The CODE is the source of truth; this greps declarations, so the map cannot drift
# (re-run after structural edits). Output is deterministic (no timestamps) → clean diffs.
# Usage: bash scripts/gen_navmap.sh   (resolves repo root from its own path; run from anywhere)
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"
out=".agent/NAVMAP.md"

# Python: classes, module-level + nested defs, route decorators, ALL_CAPS module constants.
py_pat='^(class |def |async def |    def |    async def |@(get|post|put|patch|delete|route)|[A-Z_][A-Z0-9_]+ *[:=])'
# Lean: declaration keywords (kanji «…» names follow the keyword, so they ride along).
lean_pat='^[[:space:]]*(namespace|axiom|theorem|def|abbrev|structure|inductive|instance|class) '

emit_file() {
  local f="$1" pat="$2" hits
  [ -f "$f" ] || return 0
  hits="$(grep -nE "$pat" "$f" 2>/dev/null || true)"
  [ -n "$hits" ] || return 0
  printf '\n### `%s`\n\n' "$f"
  # -F: so $1 is the grep line number; strip the "N:" prefix off $0, rtrim, wrap in backticks.
  # No length cap: declaration lines are short (params wrap to following lines), and a byte
  # cap would split multibyte kanji identifiers. Keeps this pure bash+grep+awk, UTF-8-safe.
  printf '%s\n' "$hits" | awk -F: '
    { ln=$1; sub(/^[0-9]+:/, ""); body=$0
      sub(/[[:space:]]+$/, "", body)
      printf "- L%s  `%s`\n", ln, body }'
}

{
  printf '# NAVMAP — symbol index\n\n'
  printf 'Generated by `scripts/gen_navmap.sh`; **do not hand-edit** — regenerate instead. '
  printf 'On-demand aid: grep here for a symbol, then read the file at the listed line rather than loading it whole. '
  printf 'Covers Python + Lean declarations (`L<line>`).\n'

  printf '\n## Python\n'
  for f in app.py i18n.py scenarios.py lean_decorate.py lean_vocab.py scripts/check_scenarios.py; do
    emit_file "$f" "$py_pat"
  done

  printf '\n## Lean\n'
  while IFS= read -r f; do
    emit_file "$f" "$lean_pat"
  done < <(find lean -name '*.lean' | sort)
} > "$out"

echo "wrote $out ($(wc -l < "$out") lines, $(wc -c < "$out") chars)"
